version: "3"
volumes:
  mysql_data:

services:
  fpm_php7.4:
    restart: "no"
    image: php:7.4.latest-fpm
    links:
      - mysql5.7:mysql5.7
    volumes:
      - ./etc_php7.4/etc:/usr/local/etc
      - ./etc_php7.4/no-debug-non-zts-20190902:/usr/local/lib/php/extensions/no-debug-non-zts-20190902
      - ./sharefolder:/tmp/sharefolder
      - ./www:/var/www/html
  mysql5.7:
    image: mysql:5.7.22.latest
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: ke0vfyex0yrtwjsaw6sazeivnyxegjcg
    volumes:
      - ./sharefolder:/tmp/sharefolder
      - ./etc_mysql:/etc/mysql # 数据库配置映射
      # docker volume create --name mysql_data && docker volume ls
      - mysql_data:/var/lib/mysql # 当报错的时候，可以把这行删了，这个是做的数据库数据的映射
    ports:
      - 3306:3306
#
# /etc/exports  文件加上 root  （no_root_squash） 不然出现 chown: changing ownership of '/var/lib/mysql/._ib_buffer_pool': Operation not permitted
# DataGrid: 链接：jdbc:mysql://localhost:3306?useSSL=false
#
  nginx:
    image: nginx:1.21.6.latest
    restart: "no"
    links:
      - fpm_php7.4:fpm_php7.4
    volumes:
      - ./etc_nginx:/etc/nginx
      - ./sharefolder:/tmp/sharefolder
      - ./www:/var/www/html
    ports:
      - 80:80

