version: "3"
services:
  fpm_php7.4:
    restart: "no"
    image: php:7.4.latest-fpm
    volumes:
      # - ./php7.1/php7_etc:/usr/local/etc
      # - ./php7.1/no-debug-non-zts-20160303:/usr/local/lib/php/extensions/no-debug-non-zts-20160303
      - ./sharefolder:/tmp/sharefolder
      - ./www:/var/www/html
  mysql5.7:
    image: mysql:5.7.22.latest
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: ke0vfyex0yrtwjsaw6sazeivnyxegjcg
    volumes:
      - ./sharefolder:/tmp/sharefolder
      - ./etc_mysql:/etc/mysql # 数据库配置映射
      - ./mysql_data:/var/lib/mysql # 当报错的时候，可以把这行删了，这个是做的数据库数据的映射
    ports:
      - 3306:3306
#
# DataGrid: 链接：jdbc:mysql://localhost:3306?useSSL=false
#
  nginx:
    image: nginx:1.21.6.latest
    restart: "no"
    links:
      - fpm_php7.4:fpm_php7.4
    volumes:
      - ./etc_nginx:/etc/nginx
      - ./sharefolder:/tmp/sharefolder
      - ./www:/var/www/html
    ports:
      - 80:80

