FROM ubuntu:20.04
ENV TZ=Asia/Shanghai
#COPY sources.list /etc/apt/sources.list
#RUN apt-get update \
#	&& apt-get install -y --allow-unauthenticated vim git curl zip php7.0 php7.0-mysql php7.0-gd php7.0-zip php7.0-fpm php7.0-curl php7.0-cli php7.0-readline \
#	&& apt-get install -y --allow-unauthenticated ffmpeg imagemagick jp2a php7.0-bcmath php7.0-mbstring php7.0-mcrypt \
#	# && curl -sS https://getcomposer.org/installer | php \
#	# && mv composer.phar /usr/local/bin/composer \
#	# && composer config -g repo.packagist composer https://packagist.phpcomposer.com \
#	&& ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
